//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoInfo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesInfo
    {
        public int ID { get; set; }
        public System.DateTime Datetime { get; set; }
        public int CityID { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public int Population { get; set; }
        public int UserID { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Users Users { get; set; }
    }
}
